glitter:
  image: "busybox:latest"
  volumes:
    - ../glitter:/opt/glitter
app:
  image: "busybox:latest"
  volumes:
    - .:/opt/app
php:
  build: ".docker/php"
  ports:
    - 9000
  volumes:
    - ./tmp:/opt/tmp
  volumes_from:
    - glitter
    - app
    - mysql
  links:
    - memcached
    - mysql
    - redis

web:
  image: "nginx:1.11.4-alpine"
  ports:
    - 8888:80
  volumes:
    - ./.docker/web/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  volumes_from:
    - app
    - php
  links:
    - php
#  environment:
#    - VIRTUAL_HOST=local.glitter.com

storage:
  image: 'busybox:latest'
  volumes:
    - /var/lib/mysql
  command: 'true'

mysql:
  image: 'mysql:5.7'
  ports:
    - 3306
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=glitter
    - MYSQL_USER=glitter
    - MYSQL_PASSWORD=glitter
  volumes_from:
    - storage

memcached:
  image: memcached

redis:
  image: 'redis:3-alpine'
